# Calibration parameters for RealSense Camera and LiDAR

# Intrinsic parameters for RealSense Camera (aka intern parameters)
# It's used to correct the image distortion and project 3d coordinates
realsense_camera:
  fx: 617.61    # focal length in x (in px or in dist unit)
  fy: 617.61    # focal length in y (in px or in dist unit)
  cx: 318.69    # principal point coordinate in x (in px)
  cy: 240.39    # principal point coordinate in y (in px)
  # cx and cy are the intersection between optical axis and image plan
  distortion_coefficients: [0.0, 0.0, 0.0, 0.0, 0.0]  # Assuming no distortion for simplicity

# Extrinsic parameters: transformation from LiDAR to Camera frame
extrinsics:
  translation:
    x: 0.1      # Gap between the sensors (in m)
    y: 0.0      # Height of the sensors from the ground
    z: 0.0      # Distance between the optical centers (avant/arriere direction)
  rotation:
    roll: 0.0   # Orientation in radians around x-axis
    pitch: 0.0  # Orientation in radians around y-axis
    yaw: 0.0    # Orientation in radians around z-axis

# LiDAR parameters (if needed)
lidar:
  min_range: 0.1  # Minimum range in meters
  max_range: 100.0  # Maximum range in meters
  vertical_angle_min: -15.0  # Vertical angle min in degrees
  vertical_angle_max: 15.0  # Vertical angle max in degrees

# Point Cloud Filtering parameters
#point_cloud_filtering:
#  voxel_leaf_size: 0.05  # Leaf size for voxel grid filtering in meters

# Synchronization parameters
#synchronization:
#  queue_size: 10
#  slop: 0.1  # Approximate time synchronizer slop in seconds

# Visualization parameters
#visualization:
#  show_point_cloud: true
#  show_camera_image: true

# Debugging and Logging
#debug:
#  enable_logging: true
#  log_file: "/path/to/log/file.log"

